name: Code Quality

on:
  push:
  pull_request: # Per default on opened, synchronized and reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install --frozen-lockfile
    - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install --frozen-lockfile
    - run: yarn run test
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: true