name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.release.target_commitish}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
    - run: yarn run test
    - run: yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  publish:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.release.target_commitish}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - run: yarn publish --no-git-tag-version --new-version "${{ github.event.release.tag_name }}"
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}